ALTER TABLE products ADD COLUMN genre TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN couleur TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN forme TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN matiere TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN extra_json TEXT NOT NULL DEFAULT '[]';
